---
stages:
  - build
  - deploy

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ''
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE_TAG: '0.$CI_PIPELINE_IID$envVersTag'
  # DOCKER_IMAGE_TAG: '0.231'

############## build
build:
  stage: build
  environment: development
  image:
    name: docker:18-git
  tags:
    - ebs
  only:
    refs:
      - development
      - k8s_deployment
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cp $envVars .env
    - docker build -t "$CI_REGISTRY/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME:$DOCKER_IMAGE_TAG" -f docker/Dockerfile .
    - docker images
    - docker tag $CI_REGISTRY/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME:$DOCKER_IMAGE_TAG $CI_REGISTRY/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME:latest
    - docker images
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME:$DOCKER_IMAGE_TAG

###---------------------- Deploy development ----------------####

deploy_dev:
  stage: deploy
  environment: development
  image: gitlab.devebs.net:4567/templates/images/tools:docker-git-portainer-stack-utils-01
  tags:
    - ebs
  only:
    refs:
      - development
      - k8s_deployment
  script:
     - sed -i "s|REPOSITORY|$CI_REGISTRY/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME:$DOCKER_IMAGE_TAG|g"  ./docker/docker-compose.yaml
     - bash docker/deployPortainer.sh

