apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:  ## All bases k8s objects (deployment, service and ingress).
  - k8s-deployment/deployment/
  - k8s-deployment/service/
  - k8s-deployment/service/nginx
  - k8s-deployment/ingress/

patchesStrategicMerge:  ## Additional kubernetes deployment objects patches (object specifications), all of them are merging into one deployment file.
  - k8s-deployment/overlays/security/secret-image-repository.yml
  - k8s-deployment/overlays/security/ebs-platform-secret-image-repository.yml
  - k8s-deployment/overlays/environments/app-env-variables-file.yml
  - k8s-deployment/overlays/deployment/pod-with-nginx-container.yml
  - k8s-deployment/overlays/storage/volume-claim-mount-to-nginx.yml

configMapGenerator:   ## Environments
- name: ${PROJECT_NAME}-app-env-variables-file
  env: ./.env_vars
- name: ${PROJECT_NAME}-nginx-container-configfile
  files:
    - k8s-deployment/configmap/nginx/default.conf
    - k8s-deployment/configmap/nginx/media.conf

generatorOptions:
  disableNameSuffixHash: true
  labels:
    environment: ${K8S_ENV}
  annotations:
    note: configmap-generated