version: '3.4'
services:
  planning-php:
    container_name: planning-php
    image: REPOSITORY
    environment:
      APP_NAME: "${APP_NAME}"
      APP_ENV: "${APP_ENV}"
      APP_KEY: "${APP_KEY}"
      APP_DEBUG: "${APP_DEBUG}"
      APP_URL: "${APP_URL}"
      ASSET_URL: "${ASSET_URL}"
      LOG_CHANNEL: "${LOG_CHANNEL}"
      LOG_DEPRECATIONS_CHANNEL: "${LOG_DEPRECATIONS_CHANNEL}"
      LOG_LEVEL: "${LOG_LEVEL}"
      MYSQL_CONNECTION: "${MYSQL_CONNECTION}"
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_PORT: "${MYSQL_PORT}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "${MYSQL_ALLOW_EMPTY_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      BROADCAST_DRIVER: "${BROADCAST_DRIVER}"
      CACHE_DRIVER: "${CACHE_DRIVER}"
      FILESYSTEM_DISK: "${FILESYSTEM_DISK}"
      QUEUE_CONNECTION: "${QUEUE_CONNECTION}"
      SESSION_DRIVER: "${SESSION_DRIVER}"
      SESSION_LIFETIME: "${SESSION_LIFETIME}"
      REDIS_CLIENT: "${REDIS_CLIENT}"
      MEMCACHED_HOST: "${MEMCACHED_HOST}"
      REDIS_HOST: "${REDIS_HOST}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_PORT: "${REDIS_PORT}"
      MAIL_MAILER: "${MAIL_MAILER}"
      MAIL_HOST: "${MAIL_HOST}"
      MAIL_PORT: "${MAIL_PORT}"
      MAIL_USERNAME: "${MAIL_USERNAME}"
      MAIL_PASSWORD: "${MAIL_PASSWORD}"
      MAIL_ENCRYPTION: "${MAIL_ENCRYPTION}"
      MAIL_FROM_ADDRESS: "${MAIL_FROM_ADDRESS}"
      MAIL_FROM_NAME: "${MAIL_FROM_NAME}"
      TEAMWORK_ADMIN_EMAIL: "${TEAMWORK_ADMIN_EMAIL}"
      TEAMWORK_ADMIN_PASS: "${TEAMWORK_ADMIN_PASS}"
      TEAMWORK_DOMAIN: "${TEAMWORK_DOMAIN}"
    ports:
      - ${DOCKER_APP_EXP_PORT}:80/tcp
    volumes: #appvolume
      - /var/lib/data/planning_dashboard/storage:/var/www/html/storage
    networks:
      - planning
networks:
  planning:
    driver: bridge
