version: '3.4'
services:
  planning-php:
    container_name: planning-php
    image: REPOSITORY
    environment:
    ports:
      - ${DOCKER_APP_EXP_PORT}:80/tcp
    volumes: #appvolume
      - /var/lib/data/planning_dashboard/storage:/var/www/html/storage
    networks:
      - planning
networks:
  planning:
    driver: bridge
